[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
name = "kernel"
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false

[[test]]
name = "basic_boot"
harness = false

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false

[[test]]
name = "breakpoint"
harness = false

[[test]]
name = "timer_interrupt"
harness = false

[[test]]
name = "heap_allocation"
harness = false

[[test]]
name = "executor_basic"
harness = false

[[test]]
name = "executor_multitask"
harness = false

[[test]]
name = "ramfs"
harness = false

[[test]]
name = "shell_commands"
harness = false

[[test]]
name = "ata_identify"
harness = false

[[test]]
name = "fat_read"
harness = false

[[test]]
name = "fat_write"
harness = false

[[test]]
name = "fb_scrollback"
harness = false

[[test]]
name = "tmpfs"
harness = false

[[test]]
name = "devfs"
harness = false

[[test]]
name = "ring3_jump"
harness = false

[dependencies]
bootloader_api = "0.11.12"
uart_16550 = "0.4.0"
x86_64 = "0.15.2"
spin = "0.10.0"
conquer-once = { version = "0.4.0", default-features = false }
pic8259 = "0.11.0"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.10.6"
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3.32", default-features = false, features = ["alloc"] }
noto-sans-mono-bitmap = { version = "0.3.2", default-features = false, features = [
    "regular",
    "size_16",
    "unicode-basic-latin",
    "unicode-specials",
] }
