[target.x86_64-unknown-none]
runner = "cargo run --quiet -p willo --"

[alias]
kbuild = "build -p kernel --target x86_64-unknown-none"
krun = "run -p kernel --target x86_64-unknown-none"
ktest = "test -p kernel --target x86_64-unknown-none"
